In [ ]:
import numpy as np

1) 0-29 arası(29 dahil, toplam 30 tam sayı) tam sayılardan oluşan bir boyutlu bir array oluşturun ardından bu array'in shape'ini (15,2) şeklinde güncelleyip 2 boyutlu hale getirin.

In [ ]:
arr = np.arange(0,30)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
arr.reshape(15,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

2) 60 adet rastgele tam sayı verilerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'i istediğiniz shapelerde 3 boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [ ]:
arr = np.random.randint(0,150,60)
arr

array([ 85, 140, 118,  92, 126,  42,   1, 145,  73, 148, 142,  54,  38,
        71, 149, 109,  61, 146, 135,  27,  22,  30,  70, 117,   8, 111,
       148,  50,  81, 105,  82, 128,  11,  25, 137,  73, 116,  17,  14,
       103, 119,  33,  26, 147,  46, 146,  67,  79,  90,  11,   5, 128,
        94, 112, 129,  62, 107, 118,  33,  50])

In [ ]:
arr3d = arr.reshape(6,5,-1)
arr3d

array([[[ 85, 140],
        [118,  92],
        [126,  42],
        [  1, 145],
        [ 73, 148]],

       [[142,  54],
        [ 38,  71],
        [149, 109],
        [ 61, 146],
        [135,  27]],

       [[ 22,  30],
        [ 70, 117],
        [  8, 111],
        [148,  50],
        [ 81, 105]],

       [[ 82, 128],
        [ 11,  25],
        [137,  73],
        [116,  17],
        [ 14, 103]],

       [[119,  33],
        [ 26, 147],
        [ 46, 146],
        [ 67,  79],
        [ 90,  11]],

       [[  5, 128],
        [ 94, 112],
        [129,  62],
        [107, 118],
        [ 33,  50]]])

In [ ]:
arr3d.ndim

3

In [ ]:
arr3d.shape

(6, 5, 2)

3) 20 elemanlı ve sadece rakamlardan oluşan iki boyutlu bir array oluşturun. Ardından bu array'i düzleştirin ve tek boyutlu hale getirin ve son durumda oluşan array'in boyutunu ve shape'ini kontrol edin.

In [ ]:
arr2d = np.random.randint(0,50, size=(5, 4))
arr2d

array([[ 4,  4, 38, 19],
       [28, 15, 47, 10],
       [44,  9, 45, 43],
       [26, 23, 31, 37],
       [14,  8, 33, 41]])

In [ ]:
arr = arr2d.reshape(-1)

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(20,)

4) İstediğiniz herhangi elemanlardan oluşan 2 Boyutlu bir array oluşturun. Oluşturduğunuz bu 2 boyutlu array'in içindeki bütün elemanları hem yavaş yol olan for döngüsüyle hem de daha hızlı yol olan uygun NumPy metoduyla tek tek dönerek ekrana yazdırın.

In [ ]:
arr2d = np.random.randint(0,5, size=(3,4))
arr2d

array([[2, 1, 2, 0],
       [0, 2, 3, 4],
       [4, 1, 3, 3]])

In [ ]:
for i in arr2d:
  for x in i:
    print(x)

2
1
2
0
0
2
3
4
4
1
3
3


In [ ]:
for i in np.nditer(arr2d):
  print (i)

2
1
2
0
0
2
3
4
4
1
3
3


## 5) 5,10,15,20,25,30 değerlerinden oluşan bir boyutlu bir array ve
   1,2,3,4,5,6 değerlerinden oluşan başka bir boyutlu bir array oluşturun.
   Bu arraylerinin elemanlarına kendi aralarında 4 işlem uygulayın. İki arrayinde 1.indexindekiler toplansın/çıkartılsın/çarpılsın/bölünsün gibi.

In [ ]:
arr1 = np.arange(5,31,5)
arr1

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
arr2 = np.arange(1,7)
arr2

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.add(arr1, arr2)[0]

6

In [ ]:
arr1[1].__sub__(arr2[1])

8

In [ ]:
arr1[1].__mul__(arr2[1])

20

In [ ]:
arr1[0] / arr2[0]

5.0

6) 0-100 arası rastgele 10 tam sayıdan oluşan bir array oluşturun ve oluşturulan arrayin sum/mean/max/var/std değerlerini inceleyin.


In [ ]:
arr = np.random.randint(1,50,10)
arr

array([ 8, 39, 23, 45, 19, 43,  8, 25, 18, 46])

In [ ]:
arr.sum()

274

In [ ]:
arr.mean()

27.4

In [ ]:
arr.max()

46

In [ ]:
arr.var()

197.04

In [ ]:
arr.std()

14.037093716293269

7) 0-20 arası(20 dahil değil) tam sayılardan oluşan ve 500-530(530 dahil) arası tam sayılardan oluşan 2 array oluşturun. Ardından bu iki array'i concatenate ederek ekrana yazdırın.

In [ ]:
arr1 = np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2 = np.arange(500,531)
arr2

array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530])

In [ ]:
np.concatenate([arr1,arr2], axis = 0)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 501, 502, 503, 504, 505,
       506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518,
       519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530])

8) 15-50(50 dahil) arası tam sayılardan oluşan bir array oluşturun. Daha sonra 10-100 arası(100 dahil) tam sayılardan oluşan 2.bir array oluşturun. Bu 2 arrayi concatanate ederek 3.bir array oluşturun ve bu array'in 25.index ile 50.index'i(50 dahil) arasındaki değerlerini 888 yapın.

In [ ]:
arr1 = np.arange(15,51)
arr1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50])

In [ ]:
arr2 = np.arange(10,101)
arr2

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr3 = np.concatenate([arr1, arr2], axis = 0)
arr3

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr3[25:51] = 888
arr3 

array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,
       888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888, 888,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

9) 0-40(40 dahil değil) arası değerlerden oluşan (8,5) shape'inde 2 boyutlu bir array ve  320-360(360 dahil değil) değerlerinden oluşan (8,5) shape'inde 2 boyutlubaşka bir array oluşturun. Devamında bu iki array'i hem axis = 0'da hem de axis = 1'de concatenate ederek farkı karşılaştırın.

In [ ]:
arr1 = np.arange(0,40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [ ]:
arr2 = np.arange(320,360).reshape(8,5)
arr2

array([[320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [ ]:
arr3 = np.concatenate([arr1, arr2], axis = 0)
arr3

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [320, 321, 322, 323, 324],
       [325, 326, 327, 328, 329],
       [330, 331, 332, 333, 334],
       [335, 336, 337, 338, 339],
       [340, 341, 342, 343, 344],
       [345, 346, 347, 348, 349],
       [350, 351, 352, 353, 354],
       [355, 356, 357, 358, 359]])

In [ ]:
arr4 = np.concatenate([arr1, arr2], axis = 1)
arr4

array([[  0,   1,   2,   3,   4, 320, 321, 322, 323, 324],
       [  5,   6,   7,   8,   9, 325, 326, 327, 328, 329],
       [ 10,  11,  12,  13,  14, 330, 331, 332, 333, 334],
       [ 15,  16,  17,  18,  19, 335, 336, 337, 338, 339],
       [ 20,  21,  22,  23,  24, 340, 341, 342, 343, 344],
       [ 25,  26,  27,  28,  29, 345, 346, 347, 348, 349],
       [ 30,  31,  32,  33,  34, 350, 351, 352, 353, 354],
       [ 35,  36,  37,  38,  39, 355, 356, 357, 358, 359]])

10) 9.Soruda oluşturduğunuz 2 array'i axis = 2'de concatenate etmeye çalışın. Ardından axis = 2'de stacklemeye(yığınlamaya) çalışın. İkisi arasındaki farkı karşılaştırın.

In [ ]:
## arr5 = np.concatenate([arr1, arr2], axis = 2)
## arr5

In [ ]:
arr5 = np.stack([arr1, arr2], axis = 2)
arr5

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

array([[[  0, 320],
        [  1, 321],
        [  2, 322],
        [  3, 323],
        [  4, 324]],

       [[  5, 325],
        [  6, 326],
        [  7, 327],
        [  8, 328],
        [  9, 329]],

       [[ 10, 330],
        [ 11, 331],
        [ 12, 332],
        [ 13, 333],
        [ 14, 334]],

       [[ 15, 335],
        [ 16, 336],
        [ 17, 337],
        [ 18, 338],
        [ 19, 339]],

       [[ 20, 340],
        [ 21, 341],
        [ 22, 342],
        [ 23, 343],
        [ 24, 344]],

       [[ 25, 345],
        [ 26, 346],
        [ 27, 347],
        [ 28, 348],
        [ 29, 349]],

       [[ 30, 350],
        [ 31, 351],
        [ 32, 352],
        [ 33, 353],
        [ 34, 354]],

       [[ 35, 355],
        [ 36, 356],
        [ 37, 357],
        [ 38, 358],
        [ 39, 359]]])

In [ ]:
## concaneta yapamıyoruz çünkü 2 boyutlu bir arrayimiz var. stackleme işleminde ise 2 arrayimizin de indexlerini karşılaştırarak yeni index yapıyor.


11) [1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5] değerlerinden oluşan bir boyutlu bir array oluşturun. Devamında bu array'in içinde değeri 5'e eşit olan değerlerin indexleri bulun.

In [ ]:
arr1 = np.array([1, 20, 25, 4, 4, 5, 4, 4, 1, 6, 9, 12, 1, 5])
arr1

array([ 1, 20, 25,  4,  4,  5,  4,  4,  1,  6,  9, 12,  1,  5])

In [ ]:
arr2 = np.where(arr1 == 5)[0]
arr2

array([ 5, 13])

12) Yukarıda oluşturduğunuz array içinde değeri çift olan değerlerin indexlerini bulun.

In [ ]:
arr3 = np.where(arr1 % 2 == 0)[0]
arr3

array([ 1,  3,  4,  6,  7,  9, 11])

13) Yukarıda oluşturduğunuz array içinde değeri 4'den büyük olan değerlerin indexlerini bulun.

In [ ]:
arr4 = np.where(arr1>4)[0]
arr4

array([ 1,  2,  5,  9, 10, 11, 13])

14) Yukarıda oluşturduğunuz array içinde değeri 5'e tam bölünen değerlerin indexlerini bulun.

In [ ]:
arr5 = np.where(arr1 % 5 == 0)[0]
arr5

array([ 1,  2,  5, 13])

15) 85-100(100 dahil) arasından rastgele 1 tam sayı seçin

In [ ]:
arr1 = np.random.randint(85,101)
arr1

85

16) İki basamaklı tam sayılar arasından rastgele sayılar seçerek (3,3) shape'inde bir array oluşturun.

In [ ]:
arr1 = np.random.randint(10,100, size= (3,3))
arr1

array([[80, 97, 86],
       [74, 38, 39],
       [53, 57, 75]])

17) 35-60 arasındaki tam sayılardan bir array oluşturun, ardından bu array içinden rastgele 1 tam sayı seçin.

In [ ]:
arr1 = np.arange(35,60)
arr1

array([35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
np.random.choice(arr1)

41

18) Sadece [3, 8, 10, 53] değerlerinden oluşan (2,5) shape'inde 2 boyutlu bir array oluşturun.

In [ ]:
arr1 = np.random.choice([3, 8, 10, 53], size=(2, 5))
arr1

array([[ 8,  8,  8,  3,  8],
       [ 8,  8,  3,  3, 53]])